;問題3.4
(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds"))
  (define (deposit amount)
    (begin (set! balance (+ balance amount))
           balance))
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request -- MAKE-ACCOUNT"
                       m))))
  (define (authenticate p m)
    (if (eq? password p)
      (dispatch m)
      (if (>= (auth 'how-many-calls?) 6)
        call-the-cops
        auth)))
  (define (Incorrect x)
    "Incorrect password")
  (define auth (make-monitored Incorrect))
  (define (call-the-cops x)
    "call-the-cops")
  authenticate)
